
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace La_Game.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Language_Member
{

    public int idLanguage_User { get; set; }

    public int Language_idLanguage { get; set; }

    public int Member_idMember { get; set; }



    public virtual Language Language { get; set; }

    public virtual Member Member { get; set; }

}

}
