
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace La_Game.Models
{

using System;
    using System.Collections.Generic;
    
public partial class QuestionList
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public QuestionList()
    {

        this.QuestionResults = new HashSet<QuestionResult>();

        this.QuestionList_Question = new HashSet<QuestionList_Question>();

        this.Lesson_QuestionList = new HashSet<Lesson_QuestionList>();

        this.QuestionOrders = new HashSet<QuestionOrder>();

    }


    public int idQuestionList { get; set; }

    public string questionListName { get; set; }

    public string questionListDescription { get; set; }

    public string participationCode { get; set; }

    public Nullable<short> isActive { get; set; }

    public Nullable<short> isHidden { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<QuestionResult> QuestionResults { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<QuestionList_Question> QuestionList_Question { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Lesson_QuestionList> Lesson_QuestionList { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<QuestionOrder> QuestionOrders { get; set; }

}

}
