//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace La_Game.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionOrder
    {
        public int idQuestionOrder { get; set; }
        public Nullable<double> order { get; set; }
        public int QuestionList_idQuestionList { get; set; }
        public int Question_idQuestion { get; set; }
    
        public virtual QuestionList QuestionList { get; set; }
        public virtual Question Question { get; set; }
    }
}
