//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace La_Game.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionResult
    {
        public int idQuestionResult { get; set; }
        public int QuestionList_idQuestionList { get; set; }
        public int AnswerOption_idAnswer { get; set; }
        public int Participant_idParticipant { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<int> attempt { get; set; }
    
        public virtual AnswerOption AnswerOption { get; set; }
        public virtual Participant Participant { get; set; }
        public virtual QuestionList QuestionList { get; set; }
    }
}
